CREATE TABLE CGroup (
Id INTEGER PRIMARY KEY,
Code INTEGER,
MarkId INTEGER,
CONSTRAINT MarkInd
FOREIGN KEY(MarkId) REFERENCES CIMark_(id),
Nm CHAR(50)
);

ALTER TABLE CGroup
ALTER COLUMN MarkId INTEGER 
CONSTRAINT MarkInd
REFERENCES CIMark_(id);